[package]
name = "redoor"
version = "0.1.1"
edition = "2024"

[[bin]]
name = "redoor"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.53.1", features = ["full"] }
axum = { version = "0.8.9", features = ["ws"] }
axum-extra = { version = "0.12.6", features = ["typed-header"] }
tokio-tungstenite = { version = "0.30.0", features = ["rustls-tls-native-roots"] }
futures-util = "0.3.33"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
uuid = { version = "1.24.0", features = ["serde", "v4"] }
chrono = "0.4.45"
ts-rs = "12.0.1"
sysinfo = "0.39.6"
tower-http = { version = "0.7.0", features = ["cors"] }
nix = { version = "0.31.3", features = ["user", "signal"] }
libc = "0.2"
fastrand = "2.5.0"
async-stream = "0.3.6"
bytes = "1.12.1"
mime_guess = "2.0.5"
headers = "0.4.1"
tar = "0.4.46"
clap = { version = "4.6.6", features = ["derive", "env"] }
anyhow = "1.0.104"
thiserror = "2.0.20"
reqwest = { version = "0.13.4", features = ["stream"] }
semver = "1.0.27"
axum-embed = "0.1.0"
rust-embed = "8.12.0"
toml_edit = "0.25.13"
pty-process = { version = "0.5.3", features = ["async"] }
argon2 = "0.5.3"
subtle = "2.6.1"
sha1 = "0.10.6"
sha2 = "0.10.9"
rand_core = { version = "0.6.4", features = ["getrandom"] }
nucleo-matcher = "0.3.1"

[target.'cfg(target_os = "linux")'.dependencies]
libloading = "0.9.0"
