// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One NSS group that a root details view can select as a group.
 */
export type AgentAccountGroup = { name: string, gid: number, };
