// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies the user-visible connection lifecycle independently from ownership.
 */
export type AgentConnectionStatus = "stopped" | "starting" | "connected" | "disconnected";
