// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies one agent across the router, websocket protocol, and REST API.
 *
 * This is the stable key used to address a connected agent and to associate
 * agent-originated messages with that agent.
 */
export type AgentId = string;
