// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { BinaryIdentity } from "./BinaryIdentity";
import type { MountPoint } from "./MountPoint";
import type { UnixTimestampSeconds } from "./UnixTimestampSeconds";

/**
 * Connected-agent detail view including the same binary identity as the server home.
 */
export type AgentDetailsResponse = { id: AgentId, name: string, pid: number, cwd: string, 
/**
 * Absolute path of the TOML config file this agent loaded, or empty when none.
 */
config_path: string, 
/**
 * Absolute path of the running agent binary.
 */
exe_path: string, load_average_one: number, load_average_five: number, load_average_fifteen: number, system_uptime: number, os: string, arch: string, hostname: string, 
/**
 * Primary non-loopback IP selected from the agent's local routing table.
 */
external_ip: string | null, username: string, connected_at: UnixTimestampSeconds, 
/**
 * Compile-time identity of the agent binary currently serving this connection.
 */
binary: BinaryIdentity, 
/**
 * Current filesystems are optional on the wire so newer servers can still inspect older agents.
 */
mount_points: Array<MountPoint>, 
/**
 * Effective UID of the connected agent process; defaults for older agents that omit it.
 */
uid: number, 
/**
 * Whether the connected agent process is running as root; defaults false for older agents.
 */
is_root: boolean, };
