// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentAccountGroup } from "./AgentAccountGroup";
import type { AgentAccountUser } from "./AgentAccountUser";

/**
 * Host account catalog fetched on demand so connect metadata stays small.
 */
export type AgentAccountsResponse = { users: Array<AgentAccountUser>, groups: Array<AgentAccountGroup>, 
/**
 * True when NSS returned more accounts than the agent is willing to serialize.
 */
truncated: boolean, };
