// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentConnectionStatus } from "./AgentConnectionStatus";
import type { AgentId } from "./AgentId";
import type { BinaryIdentity } from "./BinaryIdentity";
import type { UnixTimestampSeconds } from "./UnixTimestampSeconds";

/**
 * Summarizes one known agent without requiring a current WebSocket connection.
 */
export type AgentInfoResponse = { id: AgentId, name: string, cwd: string | null, managed: boolean, status: AgentConnectionStatus, connected_at: UnixTimestampSeconds | null, last_seen_at: UnixTimestampSeconds | null, connection_issue: string | null, 
/**
 * Binary identity from the latest registration; absent until first connect.
 */
binary: BinaryIdentity | null, };
