// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentConnectionStatus } from "./AgentConnectionStatus";
import type { AgentId } from "./AgentId";
import type { BinaryIdentity } from "./BinaryIdentity";
import type { ProvisioningStatusMessage } from "./ProvisioningStatusMessage";
import type { SocketId } from "./SocketId";
import type { UnixTimestampSeconds } from "./UnixTimestampSeconds";

/**
 * Summarizes one known agent without requiring a current WebSocket connection.
 */
export type AgentInfoResponse = { id: AgentId, name: string, cwd: string | null, managed: boolean, 
/**
 * Whether this managed TOML entry can be edited or deleted from the UI.
 */
configuration_editable: boolean, 
/**
 * Configured SSH destination so list views can label remotes without a second request.
 */
ssh_target: string | null, status: AgentConnectionStatus, connected_at: UnixTimestampSeconds | null, 
/**
 * Current WebSocket generation; changes whenever this agent reconnects.
 */
connection_id: SocketId | null, last_seen_at: UnixTimestampSeconds | null, connection_issue: string | null, 
/**
 * Ordered SSH start steps for the current attempt; empty for local or dormant agents.
 */
provisioning_status: Array<ProvisioningStatusMessage>, 
/**
 * Binary identity from the latest registration; absent until first connect.
 */
binary: BinaryIdentity | null, 
/**
 * Whether the latest agent session can safely complete an in-place upgrade.
 */
supports_self_exec: boolean, 
/**
 * Whether the latest agent session can launch paths in a graphical desktop.
 */
supports_native_open: boolean, 
/**
 * Whether the latest agent session can move entries to its platform trash.
 */
supports_move_to_trash: boolean, 
/**
 * Whether the latest agent session can also list and restore trash entries.
 */
supports_trash: boolean, };
