// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnixTimestampSeconds } from "./UnixTimestampSeconds";

export type AgentDetailsResponse = { id: string, name: string, pid: number, cwd: string, load_average_one: number, load_average_five: number, load_average_fifteen: number, system_uptime: number, os: string, arch: string, hostname: string, username: string, connected_at: UnixTimestampSeconds, };
