// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One NSS user that a root details view can select as an owner.
 */
export type AgentAccountUser = { name: string, uid: number, };
