// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Confirms the extracted directory was published, rather than merely accepting its HTTP body.
 */
export type ArchiveUploadResponse = { path: string, bytes_written: number, };
