// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerBuildMode } from "./ServerBuildMode";

/**
 * Non-secret compile-time identity shared by server and agent binaries.
 *
 * Kept identical on both sides so the UI can compare a connected agent against
 * the server and flag mismatched or dirty builds without probing the host.
 */
export type BinaryIdentity = { 
/**
 * `CARGO_PKG_VERSION` baked into this binary.
 */
version: string, 
/**
 * Full git commit SHA (or `unknown` when git metadata was unavailable at build).
 */
git_rev: string, 
/**
 * True when the working tree had uncommitted changes at build time.
 */
git_dirty: boolean, 
/**
 * True when HEAD was not tagged `v{version}` at build time.
 */
version_dirty: boolean, 
/**
 * Whether this binary was compiled as debug or release.
 */
build_mode: ServerBuildMode, 
/**
 * UTC compile timestamp (`YYYY-MM-DDTHH:MM:SSZ`) or `unknown`.
 */
build_date: string, };
