// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CancelTransferResponse } from "./CancelTransferResponse";

/**
 * Correlates cancellation with a caller-owned upload without scanning another client's transfer paths.
 */
export type CancelUploadRequestResponse = { request_token: string, 
/**
 * None means cancellation was accepted while destination setup was still pending.
 */
transfer: CancelTransferResponse | null, };
