// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CancelTransferStatus } from "./CancelTransferStatus";
import type { TransferId } from "./TransferId";

/**
 * Returns the public transfer and its cancellation lifecycle result.
 */
export type CancelTransferResponse = { transfer_id: TransferId, status: CancelTransferStatus, };
