// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes the idempotent result of asking the router to cancel one public transfer.
 */
export type CancelTransferStatus = "accepted" | "already_canceling" | "already_canceled";
