// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RequestId } from "./RequestId";

/**
 * Confirms which execution received cancellation without exposing a fictitious file transfer.
 */
export type CancelExecutionResponse = { execution_id: RequestId, };
