// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RequestId } from "./RequestId";

/**
 * HTTP 202 accepts retained cancellation delivery; only an agent terminal event acknowledges termination.
 */
export type CancelExecutionResponse = { execution_id: RequestId, };
