// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Controls how letter case affects path and content search matching.
 */
export type CaseSensitivity = "smart" | "sensitive" | "insensitive";
