// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Carries the ordinary 9-bit mode the details grid can display and mutate.
 */
export type ChmodPathRequest = { permissions: number, };
