// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returns the applied rwx bits so symbolic, octal, and grid views update together.
 */
export type ChmodPathResponse = { path: string, permissions: number, };
