// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Accepts name or numeric owner/group strings for an existing-entry chown.
 */
export type ChownPathRequest = { 
/**
 * User name or decimal UID; omitted when only the group should change.
 */
owner: string | null, 
/**
 * Group name or decimal GID; omitted when only the owner should change.
 */
group: string | null, };
