// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returns the followed inode's ownership so UID/GID stay in sync after a name mapping.
 */
export type ChownPathResponse = { path: string, owner: string | null, group: string | null, uid: number, gid: number, };
