// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Monotonic index of one binary chunk within a streamed transfer.
 *
 * This is used in the binary streaming protocol to preserve chunk ordering
 * across uploads, downloads, and agent-to-agent copy forwarding.
 */
export type ChunkIndex = number;
