// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies one matching physical line while keeping response text bounded.
 */
export type ContentGrepMatch = { path: string, line_number: number, line: string, line_truncated: boolean, };
