// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentGrepContextLine } from "./ContentGrepContextLine";

/**
 * Identifies one matching physical line and its independently retained context.
 */
export type ContentGrepMatch = { path: string, line_number: number, line: string, line_truncated: boolean, before_context: Array<ContentGrepContextLine>, after_context: Array<ContentGrepContextLine>, };
