// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies one bounded context line adjacent to a grep match.
 */
export type ContentGrepContextLine = { line_number: number, line: string, line_truncated: boolean, };
