// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CopyEndpoint } from "./CopyEndpoint";

export type CopyFileRequest = { source: CopyEndpoint, dest: CopyEndpoint, };
