// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CopyEndpoint } from "./CopyEndpoint";
import type { CopyExistingMode } from "./CopyExistingMode";

export type CopyFileRequest = { source: CopyEndpoint, dest: CopyEndpoint, 
/**
 * What to do when `dest.path` already exists. Omitted requests keep the historical error behavior.
 */
on_existing: CopyExistingMode, };
