// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransferId } from "./TransferId";

export type CopyFileResponse = { copy_request_id: TransferId, };
