// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Controls what copy does when the destination path already exists.
 */
export type CopyExistingMode = "error" | "override" | "merge";
