// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentInfoResponse } from "./AgentInfoResponse";

/**
 * Returns the newly visible dormant inventory record after local persistence succeeds.
 */
export type CreateLocalAgentResponse = { agent: AgentInfoResponse, };
