// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes one SSH-backed managed agent to persist and register at runtime.
 */
export type CreateSshAgentRequest = { 
/**
 * SSH host, alias, or destination accepted by the local OpenSSH client.
 */
target: string, 
/**
 * Optional explicit SSH username instead of the target or SSH config default.
 */
username: string | null, 
/**
 * Optional explicit SSH port instead of the SSH config default.
 */
ssh_port: number | null, 
/**
 * Stable managed-agent name; defaults to the target hostname when omitted.
 */
name: string | null, 
/**
 * Optional path where the remote Redoor binary is installed.
 */
remote_bin: string | null, 
/**
 * Optional initial browser directory advertised before the first connection.
 */
home: string | null, 
/**
 * Optional local path receiving SSH subprocess diagnostics.
 */
log: string | null, 
/**
 * New password to persist; omit or send empty on update to keep the existing secret.
 */
password: string | null, };
