// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Selects explicit or parent-derived ownership for a newly created filesystem entry.
 */
export type CreationOwnershipOptions = { 
/**
 * Accepts either a user name or a numeric UID resolved by the agent host.
 */
owner: string | null, 
/**
 * Accepts either a group name or a numeric GID resolved by the agent host.
 */
group: string | null, 
/**
 * Overrides the root-agent default when present.
 */
inherit_owner: boolean | null, 
/**
 * Overrides the root-agent default when present.
 */
inherit_group: boolean | null, };
