// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returns the opaque single-use credential without exposing registry internals.
 */
export type CreateOneTimeTokenResponse = { 
/**
 * UUID accepted once by the matching agent raw-download path.
 */
one_time_token: string, };
