// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Confirms that a managed SSH entry and its dormant runtime registration were removed.
 */
export type DeleteManagedAgentResponse = { deleted: boolean, };
