// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";

/**
 * Identifies one agent-side file participating in a server-generated diff.
 */
export type DiffEndpoint = { agent: AgentId, path: string, };
