// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffEndpoint } from "./DiffEndpoint";

/**
 * Selects two ordered files without requiring them to share an agent or path.
 */
export type DiffFilesRequest = { left: DiffEndpoint, right: DiffEndpoint, };
