// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returns text in the conventional unified diff representation used by patch tools.
 */
export type DiffFilesResponse = { unified_diff: string, };
