// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes one filesystem entry omitted from a partial directory-size result.
 */
export type DirectorySizeError = { path: string, error: string, };
