// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirectorySizeError } from "./DirectorySizeError";

/**
 * Returns the recursive regular-file bytes stored below one directory.
 */
export type DirectorySizeResponse = { path: string, size: number, errors: Array<DirectorySizeError>, };
