// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reports how many payload entries were permanently removed from all trash locations.
 */
export type EmptyTrashResponse = { deleted_items: number, };
