// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Byte arrays preserve binary output and split UTF-8 sequences without unbounded accumulation.
 */
export type ExecEvent = { "type": "stdout", data: Array<number>, } | { "type": "stderr", data: Array<number>, } | { "type": "exit", code: number | null, signal: number | null, } | { "type": "timed_out" } | { "type": "canceled" } | { "type": "error", message: string, };
