// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes one matching remote path without requiring additional metadata calls.
 */
export type FileSearchEntry = { name: string, path: string, type: string, };
