// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Confirms that an editor body was committed to the selected existing inode.
 */
export type FileEditResponse = { path: string, bytes_written: number, };
