// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileSearchEntry } from "./FileSearchEntry";

/**
 * Returns the best paths discovered before traversal completed or reached its deadline.
 */
export type FileSearchResponse = { results: Array<FileSearchEntry>, timed_out: boolean, duration_ms: number, };
