// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";

/**
 * Identifies an agent path and bounded filename-search controls without URL-sized query data.
 */
export type FindRequest = { agent: AgentId, path: string, query: string, timeout: number, include_hidden: boolean, respect_gitignore: boolean, };
