// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaseSensitivity } from "./CaseSensitivity";

/**
 * Carries bounded filename-search controls while the route identifies the agent and root path.
 */
export type FindRequest = { query: string, timeout: number, include_hidden: boolean, respect_gitignore: boolean, case_sensitivity: CaseSensitivity, };
