// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitEntryType } from "./GitEntryType";
import type { GitTrackingState } from "./GitTrackingState";

/**
 * Prevents repository-only context from being represented for paths outside a worktree.
 */
export type GitContextResponse = { "status": "outside_worktree" } | { "status": "inside_worktree", entry_type: GitEntryType, tracking_state: GitTrackingState | null, repository_root: string, repository_relative_path: string, };
