// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Normalizes index and worktree status into a stable public vocabulary.
 */
export type GitChangeState = "unmodified" | "added" | "modified" | "deleted" | "renamed" | "copied" | "type_changed";
