// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies entries that cannot be represented by ordinary staged/unstaged states.
 */
export type GitConflictState = "conflicted";
