// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitEntryType } from "./GitEntryType";
import type { GitTrackingState } from "./GitTrackingState";

/**
 * Provides the inexpensive Git-tab availability and file classification contract.
 */
export type GitContextResponse = { inside_worktree: boolean, entry_type: GitEntryType, tracking_state: GitTrackingState | null, repository_root: string | null, repository_relative_path: string | null, };
