// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitFileDiff } from "./GitFileDiff";

/**
 * Returns ordered per-file Git comparisons without merging their patch payloads.
 */
export type GitDiffResponse = { diffs: Array<GitFileDiff>, };
