// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents every bounded single-file diff outcome explicitly.
 */
export type GitDiffResult = { "type": "text", unified_diff: string, } | { "type": "no_changes" } | { "type": "untracked" } | { "type": "ignored" } | { "type": "binary" } | { "type": "too_large" } | { "type": "unsupported_entry" };
