// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitDiffMode } from "./GitDiffMode";

/**
 * Selects ordered files and the source compared with HEAD without exposing paths in the URL.
 */
export type GitDiffRequest = { files: Array<string>, mode: GitDiffMode, };
