// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Selects the source on the right side of a comparison with HEAD.
 */
export type GitDiffMode = "full" | "staged";
