// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitDiffMode } from "./GitDiffMode";
import type { GitDiffResult } from "./GitDiffResult";

/**
 * Returns a single-file Git comparison without repository-wide patch payloads.
 */
export type GitDiffResponse = { mode: GitDiffMode, path: string, result: GitDiffResult, };
