// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Distinguishes filesystem shapes without exposing platform metadata details.
 */
export type GitEntryType = "file" | "directory" | "symlink" | "missing" | "other";
