// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitDiffResult } from "./GitDiffResult";

/**
 * Carries one file's bounded comparison in the same order as the request.
 */
export type GitFileDiff = { path: string, result: GitDiffResult, };
