// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies the Git object kind without leaking gix mode values.
 */
export type GitStatusEntryKind = "file" | "symlink" | "submodule" | "other";
