// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitChangeState } from "./GitChangeState";
import type { GitConflictState } from "./GitConflictState";
import type { GitStatusEntryKind } from "./GitStatusEntryKind";

/**
 * Describes one changed path from the merged HEAD/index/worktree view.
 */
export type GitStatusEntry = { path: string, repository_relative_path: string, original_path: string | null, index_state: GitChangeState, worktree_state: GitChangeState, conflict_state: GitConflictState | null, entry_kind: GitStatusEntryKind, };
