// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitStatusEntry } from "./GitStatusEntry";

/**
 * Returns bounded, deterministic status for one literal directory prefix.
 */
export type GitStatusResponse = { path: string, repository_root: string, branch_name: string | null, detached_head_id: string | null, upstream: string | null, ahead: number | null, behind: number | null, entries: Array<GitStatusEntry>, truncated: boolean, omitted_non_utf8_entries: number, };
