// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes whether a browser file participates in repository tracking.
 */
export type GitTrackingState = "tracked" | "untracked" | "ignored" | "deleted";
