// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { CaseSensitivity } from "./CaseSensitivity";

/**
 * Identifies an agent path and bounded content-search controls without URL-sized query data.
 */
export type GrepRequest = { agent: AgentId, path: string, query: string, timeout: number, include_hidden: boolean, respect_gitignore: boolean, fixed_string: boolean, case_sensitivity: CaseSensitivity, before_context: number, after_context: number, };
