// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Orders log records so callers can consistently filter and present process output.
 */
export type Level = "trace" | "debug" | "info" | "warning" | "error";
