// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Level } from "./Level";
import type { LogErrorDetails } from "./LogErrorDetails";

/**
 * Represents one record identically across replay, live events, and JSON output.
 */
export type LogEntry = { 
/**
 * Uses RFC 3339 milliseconds and an explicit offset for unambiguous ordering.
 */
timestamp: string, level: Level, 
/**
 * Excludes rendered timestamp and severity prefixes.
 */
message: string, 
/**
 * Exists only for failures sent through the dedicated error logger.
 */
error: LogErrorDetails | null, };
