// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogEntry } from "./LogEntry";

/**
 * Carries bounded history and live updates for either server or agent logs.
 */
export type LogEvent = { "type": "snapshot", 
/**
 * Preserves chronological source order so the newest retained entry renders last.
 */
entries: Array<LogEntry>, 
/**
 * Explains whether persistent history was available without exposing a file path.
 */
file_logging_enabled: boolean, } | { "type": "entry", 
/**
 * Remains structured regardless of the process output sink format.
 */
entry: LogEntry, } | { "type": "lagged", 
/**
 * Quantifies missed records while remaining safe for JavaScript consumers.
 */
skipped: number, } | { "type": "error", 
/**
 * Gives the operator an actionable generic reason while details remain process-local.
 */
message: string, };
