// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Retains diagnostics separately so viewers can disclose them on demand.
 */
export type LogErrorDetails = { 
/**
 * Contains the anyhow context/source sequence, subject to a visible bound.
 */
chain: string, 
/**
 * Contains a captured backtrace when runtime capture is enabled.
 */
backtrace: string | null, };
