// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Selects operator-facing output without changing structured browser payloads.
 */
export type LogFormat = "line" | "json";
