// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Level } from "./Level";

/**
 * Returns the authoritative threshold after a read or successful update.
 */
export type LoggingLevelResponse = { level: Level, };
