// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Level } from "./Level";

/**
 * Carries a requested runtime threshold without overloading stream protocol data.
 */
export type LoggingLevelRequest = { level: Level, };
