// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Carries credentials to the login endpoint without putting secrets in the URL.
 */
export type LoginRequest = { username: string, password: string, };
