// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Confirms which configured account now owns the browser session.
 */
export type LoginResponse = { username: string, };
