// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Confirms that both the browser cookie and its server-side session were removed.
 */
export type LogoutResponse = { logged_out: boolean, };
