// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LsEntry } from "./LsEntry";

/**
 * Exposes directory entries and metadata so clients can provide alternate directory views.
 */
export type LsDirectoryResponse = { files: Array<LsEntry>, path: string, owner: string | null, group: string | null, uid: number, gid: number, permissions: number, };
