// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LsEntry = { name: string, type: string, size: number, owner: string | null, group: string | null, uid: number, gid: number, };
