// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnixTimestampSeconds } from "./UnixTimestampSeconds";

/**
 * Describes one directory entry completely enough to render and sort a file list.
 */
export type LsEntry = {
    name: string;
    type: string;
    size: number;
    owner: string | null;
    group: string | null;
    uid: number;
    gid: number;
    modified_at: UnixTimestampSeconds;
};
