// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Exposes remote file metadata needed by clients to present a useful detail view.
 */
export type LsFileResponse = { size: number, path: string, owner: string | null, group: string | null, uid: number, gid: number, permissions: number, };
