// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returns the editable TOML fields for one local managed agent.
 */
export type ManagedLocalAgentConfigurationResponse = { 
/**
 * Stable managed-agent name; defaults to the server hostname when omitted.
 */
name: string | null, 
/**
 * Optional initial browser directory advertised before the first connection.
 */
home: string | null, 
/**
 * Optional local path receiving the spawned agent process diagnostics.
 */
log: string | null, };
