// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MetadataResponse = { path: string, mime_type: string, file_size: number, is_file: boolean, is_dir: boolean, 
/**
 * True only when the agent verified the whole file is UTF-8 and small enough to edit safely.
 */
editable: boolean, 
/**
 * True only when the agent verified content magic bytes and size allow in-browser image viewing.
 */
viewable_image: boolean, 
/**
 * Outstanding process-local download tokens for this exact agent and path.
 */
one_time_tokens: Array<string>, };
