// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes one mounted filesystem for capacity checks and direct browser navigation.
 */
export type MountPoint = { 
/**
 * Absolute path where the filesystem is mounted.
 */
path: string, 
/**
 * Bytes available to the user running the agent, when reported by the platform.
 */
available_bytes: number | null, 
/**
 * Total filesystem capacity in bytes, when reported by the platform.
 */
total_bytes: number | null, 
/**
 * Filesystem format such as ext4, tmpfs, APFS, or NTFS.
 */
mount_type: string | null, };
