// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CopyEndpoint } from "./CopyEndpoint";
import type { CopyExistingMode } from "./CopyExistingMode";

/**
 * Starts one logical move between agent filesystem endpoints.
 */
export type MoveFileRequest = { source: CopyEndpoint, dest: CopyEndpoint, 
/**
 * What to do when `dest.path` already exists.
 */
on_existing: CopyExistingMode, };
