// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransferId } from "./TransferId";

/**
 * Returns the public id used to follow asynchronous move progress.
 */
export type MoveFileResponse = { move_request_id: TransferId, };
