// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Confirms that the agent's graphical desktop accepted a path-open request.
 */
export type OpenPathResponse = { 
/**
 * The absolute path passed to the platform's native launcher.
 */
path: string, };
