// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnixTimestampMillis } from "./UnixTimestampMillis";

/**
 * One sticky provisioning line so the starting UI can show SSH progress without a log stream.
 */
export type ProvisioningStatusMessage = { 
/**
 * Operator-facing step text accumulated for the current start attempt.
 */
message: string, 
/**
 * Server-side millisecond stamp so elapsed labels can show secs + ms.
 */
at: UnixTimestampMillis, };
