// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Confirms the server accepted a config reload and is about to restart.
 */
export type ReloadConfigResponse = { reloaded: boolean, };
