// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Confirms the source path was atomically moved to the requested destination.
 */
export type RenamePathResponse = { source_path: string, dest_path: string, };
