// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Carries both absolute paths needed for one agent-side filesystem rename.
 */
export type RenamePathRequest = { source_path: string, dest_path: string, };
