// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Keeps rename inside one directory so the operation remains an atomic metadata change.
 */
export type RenamePathRequest = { dir: string, old: string, new: string, };
