// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Correlates one router command request with its eventual response.
 *
 * This is used for internal command routing between the server router,
 * websocket protocol messages, stream uploads/downloads, and agent-side
 * upload session tracking.
 */
export type RequestId = number;
