// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Selects one item through opaque identifiers and supplies its restore destination.
 */
export type RestoreTrashItemRequest = { location_id: string, item_id: string, destination_path: string, };
