// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Selects one item only through opaque identifiers returned by a fresh listing.
 */
export type RestoreTrashItemRequest = { location_id: string, item_id: string, };
