// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returns the original destination after a successful atomic restore.
 */
export type RestoreTrashItemResponse = { path: string, };
