// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Confirms a server or agent accepted a restart request before its connection closes.
 */
export type RestartResponse = { restarting: boolean };
