// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentInfoResponse } from "./AgentInfoResponse";

/**
 * Confirms that the previous managed startup attempt was canceled before its replacement began.
 */
export type RetryAgentStartResponse = { agent: AgentInfoResponse, };
