// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How browser login credentials are sourced for this server process.
 */
export type ServerAuthMode = "toml" | "pam";
