// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerAuthMode } from "./ServerAuthMode";
import type { ServerBuildMode } from "./ServerBuildMode";

/**
 * Server identity and authenticated agent bootstrap settings shown on the UI home page.
 */
export type ServerInfoResponse = { 
/**
 * Filesystem and service namespace selected by `REDOOR_APP_NAME`.
 */
app_name: string, 
/**
 * Shared registration secret included so the authenticated UI can render a working agent config.
 */
agent_token: string, 
/**
 * Absolute path of the TOML config file this process loaded.
 */
config_path: string, 
/**
 * Absolute path of the running server binary.
 */
exe_path: string, 
/**
 * Whether login uses TOML credentials or system PAM.
 */
auth_mode: ServerAuthMode, 
/**
 * Primary non-loopback IP selected from the server's local routing table.
 */
external_ip: string | null, 
/**
 * Operating system of the running server executable.
 */
os: string, 
/**
 * CPU architecture of the running server executable.
 */
arch: string, 
/**
 * `CARGO_PKG_VERSION` baked into this binary.
 */
version: string, 
/**
 * Full git commit SHA (or `unknown` when git metadata was unavailable at build).
 */
git_rev: string, 
/**
 * True when the working tree had uncommitted changes at build time.
 */
git_dirty: boolean, 
/**
 * True when HEAD was not tagged `v{version}` at build time.
 */
version_dirty: boolean, 
/**
 * Whether this binary was compiled as debug or release.
 */
build_mode: ServerBuildMode, 
/**
 * UTC compile timestamp (`YYYY-MM-DDTHH:MM:SSZ`) or `unknown`.
 */
build_date: string, };
