// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cargo profile the binary was compiled with (`debug` vs `release`).
 */
export type ServerBuildMode = "debug" | "release" | "unknown";
