// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Carries bounded history and live updates over the route-scoped server-log WebSocket.
 */
export type ServerLogEvent = { "type": "snapshot", 
/**
 * Preserves chronological source order so the newest retained entry renders last.
 */
entries: Array<string>, 
/**
 * Explains whether persistent history was available without exposing a server path.
 */
file_logging_enabled: boolean, } | { "type": "entry", 
/**
 * Uses the logger's formatted output so file and live rendering stay consistent.
 */
entry: string, } | { "type": "lagged", 
/**
 * Quantifies the missed records for diagnostics while remaining safe for JavaScript.
 */
skipped: number, };
