// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentInfoResponse } from "./AgentInfoResponse";

/**
 * Confirms that intentional shutdown completed child cleanup.
 */
export type ShutdownAgentResponse = { agent: AgentInfoResponse, };
