// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies one websocket session connected to the router.
 *
 * This is used for logging and for distinguishing concurrent connections even
 * when they belong to the same logical agent over time.
 */
export type SocketId = string;
