// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentInfoResponse } from "./AgentInfoResponse";

/**
 * Confirms that a managed supervisor accepted an idempotent start request.
 */
export type StartAgentResponse = { agent: AgentInfoResponse, };
