// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Validated terminal cell dimensions shared by browser, server, and agent.
 */
export type TerminalSize = { rows: number, cols: number, };
