// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TerminalSize } from "./TerminalSize";

/**
 * Controls sent from the browser terminal to the agent PTY.
 */
export type TerminalClientMessage = { "type": "resize", size: TerminalSize, };
