// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle notifications sent from the agent terminal to the browser.
 */
export type TerminalServerMessage = { "type": "ready" } | { "type": "exit", code: number | null, signal: number | null, } | { "type": "error", message: string, };
