// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransferDirection } from "./TransferDirection";
import type { TransferProgressState } from "./TransferProgressState";

export type TransferProgressEntry = { request_id: bigint, agent_id: string, path: string, direction: TransferDirection, total_bytes: bigint, transferred_bytes: bigint, state: TransferProgressState, error: string | null, };
