// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies a public transfer or copy operation exposed to REST and UI
 * consumers.
 *
 * Unlike `RequestId`, this represents the externally visible transfer job,
 * not the internal per-agent request IDs that may be used to implement it.
 */
export type TransferId = number;
