// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { TransferId } from "./TransferId";

export type TransferProgressUpdate = { agent_id: AgentId, request_id: TransferId, transferred_bytes: number, total_bytes: number, };
