// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransferProgressEntry } from "./TransferProgressEntry";

export type TransferProgressListResponse = { transfers: Array<TransferProgressEntry>, };
