// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CopyEndpoint } from "./CopyEndpoint";
import type { TransferDirection } from "./TransferDirection";
import type { TransferId } from "./TransferId";
import type { TransferProgressState } from "./TransferProgressState";

export type TransferProgressEntry = { request_id: TransferId, agent_id: string, path: string, source: CopyEndpoint | null, dest: CopyEndpoint | null, direction: TransferDirection, total_bytes: number, transferred_bytes: number, state: TransferProgressState, error: string | null, };
