// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnixTimestampSeconds } from "./UnixTimestampSeconds";

/**
 * Describes one restorable payload while tolerating unavailable original-path metadata.
 */
export type TrashItem = { id: string, name: string, original_path: string | null, deleted_at: UnixTimestampSeconds, };
