// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrashItem } from "./TrashItem";

/**
 * Identifies one trash storage root without exposing it as a filesystem command argument.
 */
export type TrashLocation = { id: string, path: string, items: Array<TrashItem>, };
