// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrashLocation } from "./TrashLocation";

/**
 * Groups currently discoverable trash entries by their provider-selected storage location.
 */
export type TrashListResponse = { locations: Array<TrashLocation>, };
