// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unix timestamp in whole seconds since the epoch.
 *
 * This is used for registration-time metadata such as when an agent
 * connected to the router.
 */
export type UnixTimestampSeconds = number;
