// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unix timestamp in milliseconds so provisioning rows can show secs + ms.
 */
export type UnixTimestampMillis = number;
