// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes replacement local-agent settings separately from the create contract.
 */
export type UpdateLocalAgentRequest = { name: string | null, home: string | null, log: string | null, };
