// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentInfoResponse } from "./AgentInfoResponse";

/**
 * Returns the replacement dormant inventory record after a local configuration edit.
 */
export type UpdateLocalAgentResponse = { agent: AgentInfoResponse, };
