// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Replacement JSON document written through to the login account's state file.
 */
export type UpdateUserStateRequest = { 
/**
 * Uninterpreted JSON that replaces the previous document.
 */
state: unknown, };
