// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes replacement SSH settings separately from the create contract.
 */
export type UpdateSshAgentRequest = { target: string, username: string | null, ssh_port: number | null, name: string | null, remote_bin: string | null, home: string | null, log: string | null, password: string | null, 
/**
 * Distinguishes keeping an omitted password from deleting the stored secret.
 */
clear_password: boolean | null, };
