// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Selects which server-side executable should replace a connected agent.
 */
export type UpgradeAgentRequest = { "source": "published_release", target_version: string, } | { "source": "running_server" };
