// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Confirms the agent acknowledged execution of the newly installed server version.
 */
export type UpgradeAgentResponse = { upgrading: boolean, target_version: string, };
