// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * JSON document restored from the login account's state file so the UI can hydrate preferences.
 */
export type UserStateResponse = { 
/**
 * Uninterpreted JSON previously persisted for this account.
 */
state: unknown, };
